---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package and php
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      update_cache: yes
      state: latest
    when: ansible_distribution == "Ubuntu"
