---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache package and php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      update_cache: yes
      state: absent
    when: ansible_distribution == "Ubuntu"
