---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      name: net-tools
      state: 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks:
  - name: install apache package and php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      update_cache: yes
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
  - name: Install mariadb
    apt:
      name: mariadb-server
      state: latest

- hosts: file_servers
  become: true
  tasks:
  - name: Install samba
    package:
      name: samba
      state: latest
